name: Check

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version-file: './frontend/.nvmrc'

      - name: Install yarn dependencies
        run: yarn install

      - name: Lint check frontend
        run: yarn lint:check

      - name: Format check frontend
        run: yarn format:check

      - name: Build frontend
        run: yarn build
